Config = {}

Config.Category = {
	["food"] = {
        "water",
        "bread",
        "pork_congee",
        "pork_chop",
        "mama_a",
        "mama",
    },
    ["working"] = {
        "banana_tool",    
        "banana_uptool",
        "fixtool",  
        "grapewood_tool",
        "grapewood_uptool", 
        "mango_tool",
        "mango_uptool", 
        "mining_tool",
        "orange_tool",   
        "mining_uptool",
        "orange_uptool",  
        "strawbr_tool",
        "strawbr_uptool",
        "watermelon_tool",  
        "watermelon_uptool",
    },
    ["fighting"] = {
        "Aed", 
        "bandage",
        "armor",
        "vestem",
    },
    ["material"] = {
        "leather_boar",
        "leather_deer",
        "leather_panther",  
        "luckybox",
        "mango_pack",  
        "mango",
        "marijuana",   
        "meat_boar",
        "meat_deer",   
        "meat_panther",
        "medikit",  
        "metal_scrap",
        "mineralblue",  
        "orange",
        "orange_pack",    
        "oxygen_mask",
        "Box_1", 
        "Box_2",
        "Box_3",
        "diamond",   
        "diamond_nugget",
        "elunium", 
        "gold_nugget",   
        "gold",
        "goldcoin",  
        "iron",   
        "platinumcoin",
        "screw_a",   
        "screw_b",   
        "screw_c",
        "wood",   
        "metal_scrap",  
        "copper",    
        "copper_nugget",
    },
}